# 1. Perceptron 

![image](https://user-images.githubusercontent.com/54730375/137346867-c9c4d335-5560-4d13-92c6-a6d346bbcaf8.png)

In [6]:
import torch
import numpy as np

class Perceptron():
    def __init__(self, thresholds= 0.0, eta= 0.01, n_iter=10): 
        self.thresholds = thresholds                           # threshholds -> 임계값
        self.eta = eta                                           # eta -> learning rate(변화시키는 wegit값 크기)
        self.n_iter = n_iter                                     # n_iter -> 전체를 학습시키는 횟수
    
   
    def fit(self, X, y):
        self.w_ = np.zeros(1+X.shape[1])                         # w_ -> 가중치 갯수
        self.errors_ = []                                       # ex) X = 4*2 인경우 X.shape = (4,2), X.shape[1] = 2, w_ = [0,0,0]
                                                                 # errors -> 머신러닝 반복횟수에 따라 예측값과 실제 결과값이 댜른 오류횟수 저장할 변수
        
        for _ in range(self.n_iter):                             # self.n_iter 만큼 반복학습.
            errors = 0                                           # errors(초기오류횟수) = 0
            for xi, target in zip(X,y):                          # 트레이닝 데이터셋 X와 결과값 y를 각각 xi, target 변수에 대입.
                update = self.eta * (target-self.predict(xi))    # 실제 결과값과 예측값에 대한 활성함수 리턴값이 같아지면 update = 0
                self.w_[1:] += update*xi                         # 가중치 업데이트
                self.w_[0] += update                             # w[0]는 bias 라서 update만 더함
                errors += int(update != 0.0)                     # update != 0 이면 애러 횟수 1 증가
            self.errors_.append(errors)                          # 배열에 발생한 오류횟수 추가
            #print(xi)
            print(self.w_)
        
        return self
    
    def net_input(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]               # 입력 데이터와 가중치의 곱 계산
                                                                 # np.dot -> 두 벡터의 내적 혹은 행렬의 곱을 리턴.
    
    def predict(self, X):                                       # 활성함수 구현
        return np.where(self.net_input(X) > self.thresholds, 1, -1) # 입력함수의 결과값이 임계값보다 크면 1, 그렇지않으면 -1을 리턴
    
    
   

# AND 연산 구현

In [7]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])                  # 트레이닝 데이터 정의 차원: (4, 2)
y = np.array([-1, -1, -1, 1])                                   # 결과값 정의

ppn = Perceptron(eta = 0.1)
ppn.fit(X, y)
print(ppn.errors_)

[1 1]
[0.2 0.2 0.2]
[1 1]
[0.  0.4 0.2]
[1 1]
[-0.2  0.4  0.2]
[1 1]
[-0.2  0.4  0.4]
[1 1]
[-0.4  0.4  0.2]
[1 1]
[-0.4  0.4  0.2]
[1 1]
[-0.4  0.4  0.2]
[1 1]
[-0.4  0.4  0.2]
[1 1]
[-0.4  0.4  0.2]
[1 1]
[-0.4  0.4  0.2]
[1, 3, 3, 2, 1, 0, 0, 0, 0, 0]


# NN과 선형대수 관점

![image](https://user-images.githubusercontent.com/54730375/137443137-59caf964-43ed-4fcc-956b-37f8a283cb03.png)


<br> 

![image](https://user-images.githubusercontent.com/54730375/137442185-0e165550-39fd-432b-94ae-8eaea1cabd3a.png)


